{
  "type": "record",
  "name": "order_item_value",
  "namespace": "mdh.sales",
  "doc": "GERADO (spike) a partir de contracts/domains/sales/order_item.yaml — espelha dh_landing.sales__order_item_raw (menos _ingested_at).",
  "fields": [
    {
      "name": "order_id",
      "type": "string"
    },
    {
      "name": "item_seq",
      "type": "int"
    },
    {
      "name": "item_id",
      "type": "string"
    },
    {
      "name": "dc_id",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "quantity",
      "type": "int"
    },
    {
      "name": "unit_price",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 18,
        "scale": 4
      }
    },
    {
      "name": "gross_amount",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 18,
        "scale": 4
      }
    },
    {
      "name": "discount_amount",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 18,
        "scale": 4
      }
    },
    {
      "name": "total_amount",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 18,
        "scale": 4
      }
    },
    {
      "name": "created_at",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "updated_at",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "_topic",
      "type": "string"
    },
    {
      "name": "_partition",
      "type": "int"
    },
    {
      "name": "_offset",
      "type": "long"
    },
    {
      "name": "_kafka_ts",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "_op",
      "type": "string"
    },
    {
      "name": "_cdc_seq",
      "type": "long"
    },
    {
      "name": "_schema_id",
      "type": "int"
    }
  ]
}
